### ISSUE TITLE
Upgrading celery

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/OpenArticleGauge#110]
A few minor versions after the one OAG uses, a memory leak concerning celery worker timeouts was discovered and fixed. It is probably necessary to upgrade to the latest minor version of celery to avoid this issue.

http://celery.readthedocs.org/en/3.0/changelog.html#version-3-0-24

**Comment by emanuil-tolev** [comment]
Memory is fine although we got a new problem with the upgrade: #119 .
